version: '3.8'
services:
  node-server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
    ports:
      - '4002:4002'
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
    networks:
      - node-network
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
    networks:
      - node-network
  react-client:
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4001"
    depends_on:
      - node-server
    volumes:
      - ./client:/app
    networks:
      - node-network
volumes:
  mongodbdata:
networks:
  node-network:
